version: '3.3'

services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./sqlbin:/sqlbin
  web:
    build:
        context: ./webserver
        args:
          DEV_SITE: ${DEV_SITE}
    environment:
      DISABLE_SSL: ${DISABLE_SSL}
    depends_on:
      - db
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./site:/var/www/html
    stdin_open: true
    tty: true
